reader = open("tmp.txt", "r")
writer = open("doctored.txt", "w")
data = reader.read()
lines = data.splitlines()
times = []; heights = []; vels = []; accels = []; angles = []
for line in lines:
    vals = line.split(",")
    t = float(vals[0])
    h = float(vals[1])
    V = float(vals[2])
    a = float(vals[3])

    writer.write(str(t-2))
    writer.write(" ")
    writer.write(str(h-737))
    writer.write(" ")
    writer.write(str(V))
    writer.write(" ")
    writer.write(str(a))
    writer.write(" ")
    writer.write(str(0))
    writer.write("\n")